language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
    
before_script:
  - composer install

script:
  - ./vendor/bin/phpunit  --configuration phpunit.xml --coverage-text
  - ./vendor/bin/phpcs web --standard=psr2
  - ./vendor/bin/phpcs app --standard=psr2

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
